### PR TITLE
Allow support for standalone token registration (server integration)

### PR DESCRIPTION
**Pull request by ev-mark**
Additionally, metadata added for direct integration, but not implemented.

Reference: http://www.sagepay.co.uk/file/21066/download-document/TOKEN_SYSTEM_Integration_and_Protocol_Guidelines_010814.pdf

### CODE REVIEW

**Comment by judgej** [comment]
Thanks. I will look at this tomorrow, if I don't get a chance tonight.

**Comment by ev-mark** [comment]
It's probably worth testing this quite extensively as the metadata has changed (unless by reading the diff, you're comfortable it will work).

Previously ExpiryDate was declared twice in the metadata - with the first (store = true) being overwritten by the second (store = false). However I think it should be stored in both instances so that saved cards can be removed or not used when their expiry date passes.

**Comment by judgej** [comment]
I've given it an inspection, and run a few tests, and it all looks good to me. I've found a bunch of TODO messages in there that have actually been done, so I've got some tidying up to do.

Thanks for the updates. Do you have any examples of how it would be used?

**Comment by ev-mark** [comment]
All you really need to do is the following

```php
    $sagepay = new Academe\SagePay\Server();
    $sagepay->setPlatform('test'); 
    $sagepay->setTransactionModel($sagepayStorage);
    $sagepay->setStandaloneTokenFields('myvendor', 'GBP', 'http://example.com/notification');
    $sagepay->sendRegistration();
```

The same notification can be used, and a token will be returned with an expiry date and saved in the transactions table.

It allows you to take the user to the card detail registration field without actually taking any payment, which means you can take payment from that user later (e.g. after shipping), or on a recurring basis (e.g. monthly subscription).

**Pull request merged**
